# Generated by Django 3.1.4 on 2021-01-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configures',
            table='tb_configures',
        ),
    ]
